<?php

/**
 * Implementation of hook_install().
 */
function ca_video_gallery_install() {
  variable_set('ca_video_gallery_list_template', 'ca_video_gallery_list_template_one');
  variable_set('ca_video_gallery_node_template', 'ca_video_gallery_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_video_gallery_uninstall() {
  variable_del('ca_video_gallery_list_template');
  variable_del('ca_video_gallery_node_template');
}
