<?php

include_once('ca_video_gallery.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_video_gallery_perm() {
  return array('ca_video_gallery edit general settings');
}

/**
 * Implementation of hook_menu().
 */
function ca_video_gallery_menu() {
  $items['admin/settings/ca_video_gallery'] = array(
    'title' => 'Context Admin: Video Gallery',
    'description' => 'Change the look and feel of ca_video_gallery module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_video_gallery_admin_settings_form'),
    'access arguments' => array('ca_video_gallery edit general settings'),
    'file' => 'ca_video_gallery.admin.inc',
    'file path' => drupal_get_path('module', 'ca_video_gallery') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implementation of hook_ctools_plugin_directory().
 */
function ca_video_gallery_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implementation of hook_ctools_render_alter().
 */
function ca_video_gallery_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask) {
  if ($subtask['name'] == 'ca_video_gallery' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_video_gallery') . "/css/ca_video_gallery.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_video_gallery_views_pre_render(&$view) {
  if ($view->name == 'ca_video_gallery') {
    drupal_add_css(drupal_get_path('module', 'ca_video_gallery') . "/css/ca_video_gallery.css", 'module', 'all', FALSE);
  }
}
